<!DOCTYPE html> <html lang="en"> <head> 
  <meta charset="UTF-8"> <meta 
  name="viewport" 
  content="width=device-width, 
  initial-scale=1.0"> <title>Education 
  Learning Website</title>
</head> <body> <header> <nav> 
    <h1>Welcome to our Education Learning Website</h1> <p>Start learning and enhancing your skills today!</p>
    <a href="#" class="cta-button">Get Started</a>
     <ul> 
      <li><a 
        href="../content/aws-course.phtml">AWS</a></li> <li><a 
        href="../content/devops-course.phtml">DevOps</a></li> <li><a 
        href="../content/php-course.phtml">PHP</a></li> <li><a 
        href="../content/sql-course.phtml">SQL</a></li>
      </ul> </nav>
  </header>
<!-- <main> <section 
    class="featured-courses">
      <h2>Featured Courses</h2> <!-- Add 
      code for displaying featured courses 
      -->
<!--    </section> <section 
    class="testimonials">
      <h2>What our Students are Saying</h2> 
      <!-- Add code for displaying 
      testimonials -->
<!--    </section> <section class="resources"> 
      <h2>Free Resources</h2> <!-- Add code 
      for displaying free resources -->
<!--    </section> </main> <footer> <p>Copyright 
    © 2023 Education Learning Website</p>
  </footer>  -->
</body>
</html>
