<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>AWS Steps</title>
    <link href="../template/style.css" rel="stylesheet" type="text/css" />
  </head>
  <body background-image: url("https://s3.amazonaws.com/vigneshawslearning.tk/background+images/home-page.jpg.png") background-size: 100% 100% background-repeat: no-repeat background-position: center>
    <header>
      <h1>Amazon Web Services (AWS)</h1>
    </header>
	<h1>Download Steps</h1>
    <nav>
      <ul>
        <li><a href="https://s3.amazonaws.com/vigneshawslearning.tk/aws_steps/Day+1+Steps+to+Create+EC2+Instance+-+Amazon+Linux+OS.docx">Day 1 Steps to Create EC2 Instance - Amazon Linux OS</a></li>
        <li><a href="https://s3.amazonaws.com/vigneshawslearning.tk/aws_steps/Day+1+Steps+to+Create+EC2+Instance+-+Windows+OS.docx">Day 1 Steps to Create EC2 Instance - Windows OS</a></li>
        <li><a href="https://s3.amazonaws.com/vigneshawslearning.tk/aws_steps/Day+2+Steps+to+Host+Static+Webpage+on+Apache+Server+using+Amazon+Linux+EC2+Instance.docx">Day 2 Steps to Host Static Webpage on Apache Server using Amazon Linux EC2 Instance</a></li>
        <li><a href="https://s3.amazonaws.com/vigneshawslearning.tk/aws_steps/Day+2+Steps+to+Host+Static+Webpage+on+IIS+Server+using+Windows+EC2+Instance.docx">Day 2 Steps to Host Static Webpage on IIS Server using Windows EC2 Instance</a></li>
	<li><a href="https://s3.amazonaws.com/vigneshawslearning.tk/aws_steps/Day+3+Steps+to+Create+and+Attach+AMI+in+Linux+EC2+Instance.docx">Day 3 Steps to Create and Attach AMI in Linux EC2 Instance</a></li>
        <li><a href="https://s3.amazonaws.com/vigneshawslearning.tk/aws_steps/Day+3+Steps+to+Create+and+attach+Snapshot+in+Windows+EC2+Instance.docx">Day 3 Steps to Create and attach Snapshot in Windows EC2 Instance</a></li>
	<li><a href="https://s3.amazonaws.com/vigneshawslearning.tk/aws_steps/Day+3+Steps+to+Create+and+Attach+Static+Public+IP+Address+to+EC2+Instance.docx">Day 3 Steps to Create and Attach Static Public IP Address to EC2 Instance</a></li>
	<li><a href="https://s3.amazonaws.com/vigneshawslearning.tk/aws_steps/Day+3+Steps+to+Create+and+Mount+Volume+in+running+Amazon+Linux+EC2+Instance.docx">Day 3 Steps to Create and Mount Volume in running Amazon Linux EC2 Instance</a></li>
	<li><a href="https://s3.amazonaws.com/vigneshawslearning.tk/aws_steps/Day+3+Steps+to+Create+and+Mount+Volume+in+running+Windows+EC2+Instance.docx">Day 3 Steps to Create and Mount Volume in running Windows EC2 Instance</a></li>

      </ul>
    </nav>
    <footer>
      <p>&copy; 2023 Welcome to Vick Vision.</p>
    </footer>
  </body>
</html>

